onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -divider INPUTS
add wave -noupdate /tb_aley_csmultiplier/reset
add wave -noupdate /tb_aley_csmultiplier/en
add wave -noupdate /tb_aley_csmultiplier/OP_A
add wave -noupdate /tb_aley_csmultiplier/OP_B
add wave -noupdate /tb_aley_csmultiplier/CLK
add wave -noupdate -divider {TEST SIGNALS}
add wave -noupdate /tb_aley_csmultiplier/SumOut
add wave -noupdate /tb_aley_csmultiplier/Exp_SumOut
add wave -noupdate /tb_aley_csmultiplier/Test_OutS
add wave -noupdate -divider OUTPUTS
add wave -noupdate /tb_aley_csmultiplier/SumOut
add wave -noupdate /tb_aley_csmultiplier/LineNumber
add wave -noupdate /tb_aley_csmultiplier/U0/CLK
add wave -noupdate -divider INSTANTIATIONS
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/clk
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/reset
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/en
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InA
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InB
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/SumOut
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/sSumOut0
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/sSumOut1
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/sSumOut2
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/sSumOut3
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/sAoutR1
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/sAoutR2
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/sBoutR1
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/sBoutR2
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/sSumOutR1
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/sSumOutR2
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/sSumOutR3
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/sCarryOutR1
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/sCarryOutR2
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/sCarryOutR3
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/sAout1
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/sAout2
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/sCarryIn
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/sCarryOut1
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/sCarryOut2
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/sCarryOut3
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/InA
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/InB
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/SumIn
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/CarryIn
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/Aout
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/SumOut
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/CarryOut
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/sAout1
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/sAout2
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/sAout3
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/sAout4
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/sAout5
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/sAout6
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/sAout7
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/sAout8
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/s1
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/s2
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/s3
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/s4
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/s5
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/s6
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/s7
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/s8
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/c1
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/c2
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/c3
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/c4
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/c5
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/c6
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/c7
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/c8
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/InstAley_CSMSlice1/InA
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/InstAley_CSMSlice1/InB
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/InstAley_CSMSlice1/SumIn
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/InstAley_CSMSlice1/CarryIn
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/InstAley_CSMSlice1/Aout
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/InstAley_CSMSlice1/SumOut
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/InstAley_CSMSlice1/CarryOut
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/InstAley_CSMSlice1/AB
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/InstAley_CSMSlice2/InA
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/InstAley_CSMSlice2/InB
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/InstAley_CSMSlice2/SumIn
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/InstAley_CSMSlice2/CarryIn
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/InstAley_CSMSlice2/Aout
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/InstAley_CSMSlice2/SumOut
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/InstAley_CSMSlice2/CarryOut
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/InstAley_CSMSlice2/AB
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/InstAley_CSMSlice3/InA
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/InstAley_CSMSlice3/InB
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/InstAley_CSMSlice3/SumIn
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/InstAley_CSMSlice3/CarryIn
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/InstAley_CSMSlice3/Aout
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/InstAley_CSMSlice3/SumOut
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/InstAley_CSMSlice3/CarryOut
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/InstAley_CSMSlice3/AB
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/InstAley_CSMSlice4/InA
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/InstAley_CSMSlice4/InB
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/InstAley_CSMSlice4/SumIn
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/InstAley_CSMSlice4/CarryIn
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/InstAley_CSMSlice4/Aout
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/InstAley_CSMSlice4/SumOut
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/InstAley_CSMSlice4/CarryOut
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/InstAley_CSMSlice4/AB
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/InstAley_CSMSlice5/InA
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/InstAley_CSMSlice5/InB
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/InstAley_CSMSlice5/SumIn
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/InstAley_CSMSlice5/CarryIn
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/InstAley_CSMSlice5/Aout
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/InstAley_CSMSlice5/SumOut
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/InstAley_CSMSlice5/CarryOut
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/InstAley_CSMSlice5/AB
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/InstAley_CSMSlice6/InA
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/InstAley_CSMSlice6/InB
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/InstAley_CSMSlice6/SumIn
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/InstAley_CSMSlice6/CarryIn
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/InstAley_CSMSlice6/Aout
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/InstAley_CSMSlice6/SumOut
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/InstAley_CSMSlice6/CarryOut
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/InstAley_CSMSlice6/AB
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/InstAley_CSMSlice7/InA
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/InstAley_CSMSlice7/InB
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/InstAley_CSMSlice7/SumIn
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/InstAley_CSMSlice7/CarryIn
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/InstAley_CSMSlice7/Aout
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/InstAley_CSMSlice7/SumOut
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/InstAley_CSMSlice7/CarryOut
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/InstAley_CSMSlice7/AB
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/InstAley_CSMSlice8/InA
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/InstAley_CSMSlice8/InB
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/InstAley_CSMSlice8/SumIn
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/InstAley_CSMSlice8/CarryIn
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/InstAley_CSMSlice8/Aout
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/InstAley_CSMSlice8/SumOut
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/InstAley_CSMSlice8/CarryOut
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B1/InstAley_CSMSlice8/AB
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_GenReg1/clk
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_GenReg1/reset
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_GenReg1/en
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_GenReg1/InA
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_GenReg1/InB
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_GenReg1/SumIn
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_GenReg1/CarryIn
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_GenReg1/Aout
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_GenReg1/Bout
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_GenReg1/SumOut
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_GenReg1/Carryout
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_GenReg1/sAout
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_GenReg1/sBout
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_GenReg1/sSumout
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_GenReg1/scarryout
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/InA
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/InB
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/SumIn
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/CarryIn
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/Aout
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/SumOut
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/CarryOut
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/sAout1
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/sAout2
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/sAout3
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/sAout4
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/sAout5
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/sAout6
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/sAout7
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/sAout8
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/s1
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/s2
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/s3
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/s4
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/s5
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/s6
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/s7
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/s8
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/c1
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/c2
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/c3
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/c4
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/c5
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/c6
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/c7
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/c8
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/InstAley_CSMSlice1/InA
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/InstAley_CSMSlice1/InB
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/InstAley_CSMSlice1/SumIn
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/InstAley_CSMSlice1/CarryIn
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/InstAley_CSMSlice1/Aout
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/InstAley_CSMSlice1/SumOut
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/InstAley_CSMSlice1/CarryOut
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/InstAley_CSMSlice1/AB
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/InstAley_CSMSlice2/InA
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/InstAley_CSMSlice2/InB
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/InstAley_CSMSlice2/SumIn
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/InstAley_CSMSlice2/CarryIn
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/InstAley_CSMSlice2/Aout
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/InstAley_CSMSlice2/SumOut
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/InstAley_CSMSlice2/CarryOut
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/InstAley_CSMSlice2/AB
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/InstAley_CSMSlice3/InA
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/InstAley_CSMSlice3/InB
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/InstAley_CSMSlice3/SumIn
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/InstAley_CSMSlice3/CarryIn
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/InstAley_CSMSlice3/Aout
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/InstAley_CSMSlice3/SumOut
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/InstAley_CSMSlice3/CarryOut
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/InstAley_CSMSlice3/AB
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/InstAley_CSMSlice4/InA
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/InstAley_CSMSlice4/InB
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/InstAley_CSMSlice4/SumIn
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/InstAley_CSMSlice4/CarryIn
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/InstAley_CSMSlice4/Aout
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/InstAley_CSMSlice4/SumOut
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/InstAley_CSMSlice4/CarryOut
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/InstAley_CSMSlice4/AB
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/InstAley_CSMSlice5/InA
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/InstAley_CSMSlice5/InB
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/InstAley_CSMSlice5/SumIn
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/InstAley_CSMSlice5/CarryIn
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/InstAley_CSMSlice5/Aout
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/InstAley_CSMSlice5/SumOut
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/InstAley_CSMSlice5/CarryOut
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/InstAley_CSMSlice5/AB
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/InstAley_CSMSlice6/InA
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/InstAley_CSMSlice6/InB
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/InstAley_CSMSlice6/SumIn
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/InstAley_CSMSlice6/CarryIn
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/InstAley_CSMSlice6/Aout
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/InstAley_CSMSlice6/SumOut
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/InstAley_CSMSlice6/CarryOut
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/InstAley_CSMSlice6/AB
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/InstAley_CSMSlice7/InA
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/InstAley_CSMSlice7/InB
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/InstAley_CSMSlice7/SumIn
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/InstAley_CSMSlice7/CarryIn
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/InstAley_CSMSlice7/Aout
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/InstAley_CSMSlice7/SumOut
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/InstAley_CSMSlice7/CarryOut
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/InstAley_CSMSlice7/AB
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/InstAley_CSMSlice8/InA
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/InstAley_CSMSlice8/InB
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/InstAley_CSMSlice8/SumIn
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/InstAley_CSMSlice8/CarryIn
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/InstAley_CSMSlice8/Aout
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/InstAley_CSMSlice8/SumOut
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/InstAley_CSMSlice8/CarryOut
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMSlice_8B2/InstAley_CSMSlice8/AB
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_GenReg2/clk
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_GenReg2/reset
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_GenReg2/en
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_GenReg2/InA
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_GenReg2/InB
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_GenReg2/SumIn
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_GenReg2/CarryIn
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_GenReg2/Aout
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_GenReg2/Bout
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_GenReg2/SumOut
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_GenReg2/Carryout
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_GenReg2/sAout
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_GenReg2/sBout
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_GenReg2/sSumout
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_GenReg2/scarryout
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/InA
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/InB
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/SumIn
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/CarryIn
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/SumOut
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/CarryOut
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/sAout1
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/sAout2
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/sAout3
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/sAout4
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/sAout5
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/sAout6
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/sAout7
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/s1
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/s2
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/s3
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/s4
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/s5
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/s6
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/s7
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/s8
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/c1
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/c2
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/c3
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/c4
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/c5
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/c6
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/c7
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/c8
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/InstAley_CSMSlice1/InA
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/InstAley_CSMSlice1/InB
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/InstAley_CSMSlice1/SumIn
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/InstAley_CSMSlice1/CarryIn
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/InstAley_CSMSlice1/Aout
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/InstAley_CSMSlice1/SumOut
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/InstAley_CSMSlice1/CarryOut
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/InstAley_CSMSlice1/AB
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/InstAley_CSMSlice2/InA
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/InstAley_CSMSlice2/InB
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/InstAley_CSMSlice2/SumIn
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/InstAley_CSMSlice2/CarryIn
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/InstAley_CSMSlice2/Aout
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/InstAley_CSMSlice2/SumOut
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/InstAley_CSMSlice2/CarryOut
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/InstAley_CSMSlice2/AB
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/InstAley_CSMSlice3/InA
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/InstAley_CSMSlice3/InB
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/InstAley_CSMSlice3/SumIn
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/InstAley_CSMSlice3/CarryIn
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/InstAley_CSMSlice3/Aout
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/InstAley_CSMSlice3/SumOut
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/InstAley_CSMSlice3/CarryOut
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/InstAley_CSMSlice3/AB
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/InstAley_CSMSlice4/InA
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/InstAley_CSMSlice4/InB
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/InstAley_CSMSlice4/SumIn
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/InstAley_CSMSlice4/CarryIn
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/InstAley_CSMSlice4/Aout
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/InstAley_CSMSlice4/SumOut
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/InstAley_CSMSlice4/CarryOut
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/InstAley_CSMSlice4/AB
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/InstAley_CSMSlice5/InA
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/InstAley_CSMSlice5/InB
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/InstAley_CSMSlice5/SumIn
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/InstAley_CSMSlice5/CarryIn
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/InstAley_CSMSlice5/Aout
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/InstAley_CSMSlice5/SumOut
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/InstAley_CSMSlice5/CarryOut
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/InstAley_CSMSlice5/AB
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/InstAley_CSMSlice6/InA
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/InstAley_CSMSlice6/InB
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/InstAley_CSMSlice6/SumIn
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/InstAley_CSMSlice6/CarryIn
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/InstAley_CSMSlice6/Aout
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/InstAley_CSMSlice6/SumOut
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/InstAley_CSMSlice6/CarryOut
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/InstAley_CSMSlice6/AB
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/InstAley_CSMSlice7/InA
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/InstAley_CSMSlice7/InB
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/InstAley_CSMSlice7/SumIn
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/InstAley_CSMSlice7/CarryIn
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/InstAley_CSMSlice7/Aout
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/InstAley_CSMSlice7/SumOut
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/InstAley_CSMSlice7/CarryOut
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/InstAley_CSMSlice7/AB
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/InstAley_CSMLastSlice/InA
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/InstAley_CSMLastSlice/InB
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/InstAley_CSMLastSlice/SumIn
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/InstAley_CSMLastSlice/CarryIn
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/InstAley_CSMLastSlice/SumOut
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/InstAley_CSMLastSlice/CarryOut
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_CSMLastSlice_8B/InstAley_CSMLastSlice/AB
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_GenReg3/clk
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_GenReg3/reset
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_GenReg3/en
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_GenReg3/SumIn
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_GenReg3/CarryIn
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_GenReg3/SumOut
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_GenReg3/Carryout
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_GenReg3/sSumout
add wave -noupdate /tb_aley_csmultiplier/InstAley_CSMultiplier/InstAley_GenReg3/scarryout
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {0 ns} 0}
quietly wave cursor active 0
configure wave -namecolwidth 307
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ns} {208 ns}
